#!/bin/bash -ex

#
# clean_externals
# SwiftGit2
#
# Removes the outputs from the various static library targets.
# Necessary when switching platforms/architectures as Xcode does not clean
# these for you.
#

# A list of external libraries included in the SwiftGit2 framework
libraries=(
    External/lib*.dylib
    External/libgit2/build
    External/openssl/lib/libssl.a
    External/openssl/lib/libcrypto.a
    External/openssl/include
)

rm -vrf ${libraries[@]}
