#!/bin/sh

set -e
set -x
# augment path to help it find cmake installed in /usr/local/bin,
# e.g. via brew. Xcode's Run Script phase doesn't seem to honor
# ~/.MacOSX/environment.plist
PATH="/usr/local/bin:$PATH"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig"

product="libgit2.dylib"

if [ "External/${product}" -nt "External/libgit2" ]
then
    echo "No update needed."
    exit 0
fi

cd "External/libgit2"

if [ -d "build" ]; then
    rm -rf "build"
fi

mkdir build
cd build

cmake -DBUILD_SHARED_LIBS:BOOL=ON \
    -DLIBSSH2_INCLUDE_DIRS:PATH=/usr/local/include/ \
    -DBUILD_CLAR:BOOL=OFF \
    -DTHREADSAFE:BOOL=ON \
    ..
cmake --build .

cp -av lib*.dylib ../..

echo "libgit2 has been updated."
