#!/bin/bash

set -e

# augment path to help it find cmake installed in /usr/local/bin,
# e.g. via brew. Xcode's Run Script phase doesn't seem to honor
# ~/.MacOSX/environment.plist
PATH="/usr/local/bin:$PATH"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig"

LIBRARY_NAME="libssh2.dylib"

if [ "External/${LIBRARY_NAME}" -nt "External/libssh2" ]
then
    echo "No update needed."
    exit 0
fi

cd "External/libssh2"
if [ -d "build" ]; then
    rm -rf "build"
fi
mkdir build
cd build

cmake -DBUILD_SHARED_LIBS=ON \
    -DENABLE_ZLIB_COMPRESSION=ON \
    ..
cmake --build .

cp -av src/lib*.dylib ../..

echo "libssh2 has been updated."
