#!/bin/sh

set -e
set -x
# augment path to help it find cmake installed in /usr/local/bin,
# e.g. via brew. Xcode's Run Script phase doesn't seem to honor
# ~/.MacOSX/environment.plist
PATH="$(pwd)/External:/usr/local/bin:$PATH"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig"

product="git2.framework/git2"

if [ "${product}" -nt "External/libgit2" ]
then
    echo "No update needed."
    exit 0
fi

cd "External/libgit2"
if [ -d "build" ]; then
    rm -rf "build"
fi
mkdir build
cd build

cmake -DBUILD_SHARED_LIBS:BOOL=ON \
    -DLIBSSH2_INCLUDE_DIRS:PATH=$(pwd)/External/libssh2/include \
    -DBUILD_CLAR:BOOL=OFF \
    -DTHREADSAFE:BOOL=ON \
    -DUSE_GSSAPI:BOOL=ON \
    ..
cmake --build .

rsync -av --copy-links libgit2.dylib ../../../git2.framework/git2
cd "../../../git2.framework"
install_name_tool -id @rpath/git2.framework/git2 git2

echo "git2.framework has been updated."
